/**
 * BiLSTM Landmark Extractor
 * Extracts the 8 lower-body landmarks needed for BiLSTM gait analysis
 * from the pose JSON files generated by MediaPipe
 */

/**
 * MediaPipe Pose Landmark indices (0-32)
 * We only need lower body landmarks for gait analysis
 */
export const BiLSTMLandmarkIndices = {
  LEFT_HIP: 23,
  RIGHT_HIP: 24,
  LEFT_KNEE: 25,
  RIGHT_KNEE: 26,
  LEFT_ANKLE: 27,
  RIGHT_ANKLE: 28,
  LEFT_FOOT_INDEX: 31,
  RIGHT_FOOT_INDEX: 32,
} as const;

/**
 * Landmark point structure from MediaPipe pose JSON
 */
export interface PoseLandmark {
  x: number;
  y: number;
  z: number;
  visibility: number;
}

/**
 * Frame data from pose JSON file
 */
export interface PoseFrame {
  frame: number;
  timestamp: number;
  landmarks: PoseLandmark[];
}

/**
 * Complete pose JSON structure
 */
export interface PoseJsonData {
  metadata: {
    frame_count: number;
    width: number;
    height: number;
    fps: number;
  };
  frames: PoseFrame[];
}

/**
 * Extract the 8 BiLSTM landmarks from a single frame
 * Returns array of [x, y] coordinates (16 values total)
 */
export function extractBiLSTMLandmarksFromFrame(
  landmarks: PoseLandmark[]
): number[] | null {
  if (!landmarks || landmarks.length < 33) {
    console.warn("Invalid landmarks array - expected 33 landmarks");
    return null;
  }

  const indices = Object.values(BiLSTMLandmarkIndices);
  const extracted: number[] = [];

  for (const index of indices) {
    const landmark = landmarks[index];
    if (!landmark || landmark.visibility < 0.5) {
      // Skip frames with low visibility
      return null;
    }
    // Only use x, y coordinates (normalized 0-1)
    extracted.push(landmark.x, landmark.y);
  }

  return extracted;
}

/**
 * Extract BiLSTM landmark sequences from pose JSON file
 * @param poseData - Complete pose JSON data
 * @param targetFrames - Number of frames to extract (default: 60)
 * @returns Array of shape [60, 16] or null if insufficient data
 */
export function extractBiLSTMSequence(
  poseData: PoseJsonData,
  targetFrames: number = 60
): number[][] | null {
  if (!poseData || !poseData.frames || poseData.frames.length === 0) {
    console.error("Invalid pose data");
    return null;
  }

  const frames = poseData.frames;

  // Extract landmarks from all valid frames
  const validFrames: number[][] = [];
  for (const frame of frames) {
    const landmarks = extractBiLSTMLandmarksFromFrame(frame.landmarks);
    if (landmarks) {
      validFrames.push(landmarks);
    }
  }

  if (validFrames.length === 0) {
    console.error("No valid frames found");
    return null;
  }

  // Ensure we have exactly targetFrames
  const sequence = prepareSequenceForModel(validFrames, targetFrames);
  if (!sequence) {
    console.error(`Failed to prepare sequence of ${targetFrames} frames`);
    return null;
  }

  // Normalize the sequence
  return normalizeLandmarks(sequence);
}

/**
 * Prepare sequence to have exactly targetFrames
 * Uses interpolation if needed
 */
function prepareSequenceForModel(
  frames: number[][],
  targetFrames: number
): number[][] | null {
  if (frames.length === 0) return null;

  if (frames.length === targetFrames) {
    return frames;
  }

  if (frames.length < targetFrames) {
    // Interpolate to get more frames
    return interpolateFrames(frames, targetFrames);
  }

  // Sample frames evenly if we have too many
  return sampleFrames(frames, targetFrames);
}

/**
 * Sample frames evenly from a longer sequence
 */
function sampleFrames(frames: number[][], targetCount: number): number[][] {
  const result: number[][] = [];
  const step = frames.length / targetCount;

  for (let i = 0; i < targetCount; i++) {
    const index = Math.floor(i * step);
    result.push([...frames[index]]);
  }

  return result;
}

/**
 * Interpolate frames to reach target count
 */
function interpolateFrames(
  frames: number[][],
  targetCount: number
): number[][] {
  if (frames.length === 0) return [];
  if (frames.length === 1) {
    // Repeat single frame
    return Array(targetCount).fill([...frames[0]]);
  }

  const result: number[][] = [];
  const step = (frames.length - 1) / (targetCount - 1);

  for (let i = 0; i < targetCount; i++) {
    const pos = i * step;
    const index1 = Math.floor(pos);
    const index2 = Math.min(index1 + 1, frames.length - 1);
    const t = pos - index1;

    // Linear interpolation
    const interpolated = frames[index1].map((val, j) => {
      return val * (1 - t) + frames[index2][j] * t;
    });

    result.push(interpolated);
  }

  return result;
}

/**
 * Normalize landmarks to zero mean and unit variance
 * Applied per coordinate across all frames
 */
export function normalizeLandmarks(sequence: number[][]): number[][] {
  if (sequence.length === 0) return sequence;

  const numFeatures = sequence[0].length;
  const normalized: number[][] = sequence.map((frame) => [...frame]);

  // Normalize each feature dimension
  for (let feature = 0; feature < numFeatures; feature++) {
    // Calculate mean and std for this feature
    let sum = 0;
    let sumSquared = 0;
    for (const frame of sequence) {
      const value = frame[feature];
      sum += value;
      sumSquared += value * value;
    }

    const mean = sum / sequence.length;
    const variance = sumSquared / sequence.length - mean * mean;
    const std = Math.sqrt(Math.max(variance, 1e-8)); // Avoid division by zero

    // Normalize
    for (let i = 0; i < normalized.length; i++) {
      normalized[i][feature] = (sequence[i][feature] - mean) / std;
    }
  }

  return normalized;
}

/**
 * Validate if pose data has sufficient quality for analysis
 */
export function validatePoseDataQuality(poseData: PoseJsonData): {
  valid: boolean;
  message?: string;
  validFrameCount?: number;
} {
  if (!poseData || !poseData.frames) {
    return { valid: false, message: "Invalid pose data structure" };
  }

  if (poseData.frames.length === 0) {
    return { valid: false, message: "No frames found in pose data" };
  }

  // Count frames with valid landmarks
  let validFrames = 0;
  for (const frame of poseData.frames) {
    const landmarks = extractBiLSTMLandmarksFromFrame(frame.landmarks);
    if (landmarks) {
      validFrames++;
    }
  }

  if (validFrames < 20) {
    return {
      valid: false,
      message: `Insufficient valid frames: ${validFrames}/60 required`,
      validFrameCount: validFrames,
    };
  }

  return { valid: true, validFrameCount: validFrames };
}
